# pylint: skip-file
"""Added guilds table

Revision ID: 4883030f2a54
Revises: 
Create Date: 2024-05-28 18:50:46.029953+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4883030f2a54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('discord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    # ### end Alembic commands ###
