# pylint: skip-file
"""last activity user and membership fields

Revision ID: 30e2cc632c47
Revises: eb641f2b605c
Create Date: 2024-09-01 19:45:21.707056+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e2cc632c47'
down_revision = 'eb641f2b605c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('memberships', sa.Column('last_activity_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_activity_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_type')
    op.drop_column('users', 'last_activity')
    op.drop_column('memberships', 'last_activity_type')
    op.drop_column('memberships', 'last_activity')
    # ### end Alembic commands ###
