"""birthday event id membership field

Revision ID: 35738600e80c
Revises: f7148a3c7b20
Create Date: 2024-12-27 16:42:32.639884+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35738600e80c'
down_revision = 'f7148a3c7b20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('birthday_event_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'birthday_event_id')
    # ### end Alembic commands ###
