"""mailboxes

Revision ID: fd09053d1fb0
Revises: 3a8e7ff77c93
Create Date: 2025-05-16 20:49:40.785403+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd09053d1fb0'
down_revision = '3a8e7ff77c93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('local_part', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('max_mailboxes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_mailboxes')
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
